insert into BOOK (Bookid, Title, Copies, Publisher) values (1, 'Gold', 20, 'Beer LLC');
insert into BOOK (Bookid, Title, Copies, Publisher) values (2, 'Year of the Yao, The', 4, 'Baumbach, Harvey and Nienow');
insert into BOOK (Bookid, Title, Copies, Publisher) values (3, 'Tremors II: Aftershocks', 18, 'Bruen and Sons');
insert into BOOK (Bookid, Title, Copies, Publisher) values (4, 'Letter, The', 14, 'Robel, Roob and Orn');
insert into BOOK (Bookid, Title, Copies, Publisher) values (5, 'Perfect Score, The', 1, 'Leannon-Hodkiewicz');
insert into BOOK (Bookid, Title, Copies, Publisher) values (6, 'Newton Boys, The', 9, 'Sauer-Rosenbaum');
insert into BOOK (Bookid, Title, Copies, Publisher) values (7, 'Because You''re Mine', 14, 'McCullough, Ullrich and Sporer');
insert into BOOK (Bookid, Title, Copies, Publisher) values (8, 'Mission Congo', 27, 'Kertzmann and Sons');
insert into BOOK (Bookid, Title, Copies, Publisher) values (9, 'Lady Snowblood (Shurayukihime)', 14, 'Wolff, Aufderhar and Barton');
insert into BOOK (Bookid, Title, Copies, Publisher) values (10, 'Mystics in Bali (Leák)', 27, 'Feeney-White');
insert into BOOK (Bookid, Title, Copies, Publisher) values (11, 'Easier with Practice', 20, 'Ullrich LLC');
insert into BOOK (Bookid, Title, Copies, Publisher) values (12, 'No Man''s Land', 26, 'Botsford, Wilkinson and Lockman');
insert into BOOK (Bookid, Title, Copies, Publisher) values (13, 'Iron Sky', 19, 'Runolfsson, Romaguera and Shanahan');
insert into BOOK (Bookid, Title, Copies, Publisher) values (14, 'The Butterfly Effect', 17, 'Schultz-Schinner');
insert into BOOK (Bookid, Title, Copies, Publisher) values (15, 'Private Parts', 13, 'Funk-Roberts');
insert into BOOK (Bookid, Title, Copies, Publisher) values (16, 'Homevideo', 25, 'Fisher, Kling and Donnelly');
insert into BOOK (Bookid, Title, Copies, Publisher) values (17, 'Son of Godzilla (Kaijûtô no kessen: Gojira no musuko)', 29, 'Torp-Heidenreich');
insert into BOOK (Bookid, Title, Copies, Publisher) values (18, 'You Killed Me First', 4, 'Steuber Group');
insert into BOOK (Bookid, Title, Copies, Publisher) values (19, 'Things You Can Tell Just by Looking at Her', 25, 'Sporer, Ortiz and Robel');
insert into BOOK (Bookid, Title, Copies, Publisher) values (20, 'Pied Piper, The (Pied Piper of Hamelin, The)', 6, 'Predovic-Braun');
insert into BOOK (Bookid, Title, Copies, Publisher) values (21, 'Eight Miles High (Das wilde Leben)', 23, 'Dibbert-Hills');
insert into BOOK (Bookid, Title, Copies, Publisher) values (22, 'Beethoven''s 5th', 8, 'Greenholt Inc');
insert into BOOK (Bookid, Title, Copies, Publisher) values (23, 'Avengers, The', 6, 'Kshlerin-Herzog');
insert into BOOK (Bookid, Title, Copies, Publisher) values (24, 'Surviving Picasso', 24, 'West-Ritchie');
insert into BOOK (Bookid, Title, Copies, Publisher) values (25, 'Sincerely Yours', 8, 'Hagenes, Hintz and Kerluke');
insert into BOOK (Bookid, Title, Copies, Publisher) values (26, 'Emma''s Bliss (Emmas Glück)', 8, 'Bergnaum and Sons');
insert into BOOK (Bookid, Title, Copies, Publisher) values (27, 'Attila (Attila Flagello di Dio)', 1, 'Haley-Jones');
insert into BOOK (Bookid, Title, Copies, Publisher) values (28, 'Petrified Forest, The', 19, 'Haag Group');
insert into BOOK (Bookid, Title, Copies, Publisher) values (29, 'Hound of the Baskervilles, The', 8, 'Dicki Inc');
insert into BOOK (Bookid, Title, Copies, Publisher) values (30, 'Assembly (Ji jie hao) ', 9, 'Ruecker, Heathcote and Parisian');
insert into BOOK (Bookid, Title, Copies, Publisher) values (31, 'Possible Worlds', 23, 'Deckow-Barton');
insert into BOOK (Bookid, Title, Copies, Publisher) values (32, 'Going the Distance', 8, 'Stroman-McLaughlin');
insert into BOOK (Bookid, Title, Copies, Publisher) values (33, 'Rashomon (Rashômon)', 20, 'Heidenreich-Keeling');
insert into BOOK (Bookid, Title, Copies, Publisher) values (34, 'Full Moon High', 15, 'Roberts-Green');
insert into BOOK (Bookid, Title, Copies, Publisher) values (35, 'Thing: Terror Takes Shape, The', 25, 'Jerde-Borer');
insert into BOOK (Bookid, Title, Copies, Publisher) values (36, 'Reap the Wild Wind', 21, 'Bogan-Hayes');
insert into BOOK (Bookid, Title, Copies, Publisher) values (37, 'Bad Day at Black Rock', 14, 'Moore Inc');
insert into BOOK (Bookid, Title, Copies, Publisher) values (38, 'Playing by Heart', 7, 'Stracke Inc');
insert into BOOK (Bookid, Title, Copies, Publisher) values (39, 'Down From the Mountain', 15, 'Gusikowski, Greenholt and Kunde');
insert into BOOK (Bookid, Title, Copies, Publisher) values (40, 'Second Jungle Book: Mowgli & Baloo, The', 24, 'Rolfson Inc');
insert into BOOK (Bookid, Title, Copies, Publisher) values (41, 'Catch-22', 24, 'O''Conner, Trantow and Lebsack');
insert into BOOK (Bookid, Title, Copies, Publisher) values (42, 'Deadly Surveillance', 10, 'Dickens-VonRueden');
insert into BOOK (Bookid, Title, Copies, Publisher) values (43, 'Zeus and Roxanne', 3, 'Sawayn, Rempel and Doyle');
insert into BOOK (Bookid, Title, Copies, Publisher) values (44, '1911 (Xinhai geming)', 7, 'Hessel, Bayer and Keeling');
insert into BOOK (Bookid, Title, Copies, Publisher) values (45, 'Secret, The', 22, 'Larkin and Sons');
insert into BOOK (Bookid, Title, Copies, Publisher) values (46, 'Million to Juan, A', 13, 'Wilkinson-Schulist');
insert into BOOK (Bookid, Title, Copies, Publisher) values (47, 'Burke and Hare', 18, 'Halvorson and Sons');
insert into BOOK (Bookid, Title, Copies, Publisher) values (48, 'Karla', 12, 'Quigley-Hartmann');
insert into BOOK (Bookid, Title, Copies, Publisher) values (49, '6ixtynin9 (Ruang Talok 69)', 3, 'Gleason, Nolan and Koepp');
insert into BOOK (Bookid, Title, Copies, Publisher) values (50, 'Face of Another, The (Tanin no kao)', 8, 'Miller, Zulauf and Grimes');
insert into BOOK (Bookid, Title, Copies, Publisher) values (51, 'Heavyweights (Heavy Weights)', 26, 'Barton and Sons');
insert into BOOK (Bookid, Title, Copies, Publisher) values (52, 'Promised Life, The (Vie promise, La)', 25, 'Walker-Boyle');
insert into BOOK (Bookid, Title, Copies, Publisher) values (53, 'December 7th', 23, 'Brakus, Thompson and Zemlak');
insert into BOOK (Bookid, Title, Copies, Publisher) values (54, 'And the Band Played On', 28, 'Kreiger-Runolfsdottir');
insert into BOOK (Bookid, Title, Copies, Publisher) values (55, 'Particle Fever', 13, 'Morissette and Sons');
insert into BOOK (Bookid, Title, Copies, Publisher) values (56, 'Come Out and Play', 15, 'Schmeler-Keebler');
insert into BOOK (Bookid, Title, Copies, Publisher) values (57, 'Amsterdamned', 4, 'Herzog, Bashirian and Grimes');
insert into BOOK (Bookid, Title, Copies, Publisher) values (58, 'Thin Blue Lie, The', 9, 'Wolf-Ritchie');
insert into BOOK (Bookid, Title, Copies, Publisher) values (59, 'Steamboy (Suchîmubôi)', 9, 'Senger-MacGyver');
insert into BOOK (Bookid, Title, Copies, Publisher) values (60, 'Thirteen, The (Trinadtsat)', 15, 'Leannon, Beahan and Feeney');
insert into BOOK (Bookid, Title, Copies, Publisher) values (61, 'Eat', 6, 'Wuckert Inc');
insert into BOOK (Bookid, Title, Copies, Publisher) values (62, 'Torn Curtain', 3, 'Schmidt, Hintz and Spinka');
insert into BOOK (Bookid, Title, Copies, Publisher) values (63, 'A Short History of Decay', 26, 'Cremin, Bartoletti and Braun');
insert into BOOK (Bookid, Title, Copies, Publisher) values (64, 'World of Kanako, The (Kawaki.)', 29, 'Bogisich, Parisian and Dickens');
insert into BOOK (Bookid, Title, Copies, Publisher) values (65, 'Killer Movie', 11, 'Boehm-Hahn');
insert into BOOK (Bookid, Title, Copies, Publisher) values (66, 'Phantom, The', 28, 'Crona-Zulauf');
insert into BOOK (Bookid, Title, Copies, Publisher) values (67, 'A Pigeon Sat on a Branch Reflecting on Existence', 21, 'Nikolaus-Schuster');
insert into BOOK (Bookid, Title, Copies, Publisher) values (68, 'Mr. Wonderful', 15, 'Kulas-Balistreri');
insert into BOOK (Bookid, Title, Copies, Publisher) values (69, 'All About Lily Chou-Chou (Riri Shushu no subete)', 18, 'Schaden-Trantow');
insert into BOOK (Bookid, Title, Copies, Publisher) values (70, 'Year of the Dog', 2, 'Anderson, Mayer and Ritchie');
insert into BOOK (Bookid, Title, Copies, Publisher) values (71, 'Wicker Man, The', 13, 'Crooks, Ratke and Jerde');
insert into BOOK (Bookid, Title, Copies, Publisher) values (72, 'Svampe', 6, 'King, Swift and Hansen');
insert into BOOK (Bookid, Title, Copies, Publisher) values (73, 'My Wife Is a Gangster 2 (Jopog manura 2: Dolaon jeonseol)', 22, 'Fay, Luettgen and Cassin');
insert into BOOK (Bookid, Title, Copies, Publisher) values (74, 'Breathe In', 12, 'Weimann, Jaskolski and Denesik');
insert into BOOK (Bookid, Title, Copies, Publisher) values (75, 'Tron: Legacy', 20, 'Howe LLC');
insert into BOOK (Bookid, Title, Copies, Publisher) values (76, 'Sure Thing, The', 20, 'Muller-Sporer');
insert into BOOK (Bookid, Title, Copies, Publisher) values (77, 'Beneath the Valley of the Ultra-Vixens', 21, 'Lueilwitz and Sons');
insert into BOOK (Bookid, Title, Copies, Publisher) values (78, 'Forget Baghdad: Jews and Arabs - The Iraqi Connection', 28, 'Kozey-Berge');
insert into BOOK (Bookid, Title, Copies, Publisher) values (79, 'Wreck-It Ralph', 10, 'Conn LLC');
insert into BOOK (Bookid, Title, Copies, Publisher) values (80, 'Mark, The', 17, 'Bergstrom, Bednar and Heller');
insert into BOOK (Bookid, Title, Copies, Publisher) values (81, 'Kolya (Kolja)', 12, 'Boyer Group');
insert into BOOK (Bookid, Title, Copies, Publisher) values (82, 'Mercy ', 22, 'Hagenes, Rath and Hintz');
insert into BOOK (Bookid, Title, Copies, Publisher) values (83, 'Reckless', 16, 'Schmeler Group');
insert into BOOK (Bookid, Title, Copies, Publisher) values (84, 'True Grit', 19, 'Johns Inc');
insert into BOOK (Bookid, Title, Copies, Publisher) values (85, 'Chopping Mall (a.k.a. Killbots)', 6, 'Feest, Marquardt and Bode');
insert into BOOK (Bookid, Title, Copies, Publisher) values (86, 'Stuck on You', 29, 'Herzog LLC');
insert into BOOK (Bookid, Title, Copies, Publisher) values (87, 'Spy Who Came in from the Cold, The', 14, 'Flatley LLC');
insert into BOOK (Bookid, Title, Copies, Publisher) values (88, 'My First War', 15, 'Carroll, Fisher and Grant');
insert into BOOK (Bookid, Title, Copies, Publisher) values (89, 'Day Night Day Night', 4, 'Reilly, Rath and Hilpert');
insert into BOOK (Bookid, Title, Copies, Publisher) values (90, 'Kicked in the Head', 3, 'Kulas, Kerluke and Oberbrunner');
insert into BOOK (Bookid, Title, Copies, Publisher) values (91, 'Underworld: Awakening', 7, 'Pacocha, Donnelly and Blick');
insert into BOOK (Bookid, Title, Copies, Publisher) values (92, 'Shoeshine (Sciuscià)', 3, 'Okuneva LLC');
insert into BOOK (Bookid, Title, Copies, Publisher) values (93, 'Montana', 25, 'Breitenberg-Spinka');
insert into BOOK (Bookid, Title, Copies, Publisher) values (94, 'How Do You Know', 8, 'Wilderman, Harris and Schuppe');
insert into BOOK (Bookid, Title, Copies, Publisher) values (95, 'Vampire Bat, The', 22, 'White Inc');
insert into BOOK (Bookid, Title, Copies, Publisher) values (96, 'Kingdom, The', 19, 'Purdy LLC');
insert into BOOK (Bookid, Title, Copies, Publisher) values (97, 'World Traveler', 2, 'Zieme and Sons');
insert into BOOK (Bookid, Title, Copies, Publisher) values (98, 'Moon Warriors, The (Zhan shen chuan shuo)', 21, 'Oberbrunner, Rowe and Wilkinson');
insert into BOOK (Bookid, Title, Copies, Publisher) values (99, 'Gigi', 29, 'Satterfield, Conroy and McDermott');
insert into BOOK (Bookid, Title, Copies, Publisher) values (100, 'Election Day', 26, 'Ferry-Kozey');
