insert into PERSONATYPE (PersonaTypeid, BookLimit, DaysLimit) values (1, 20, 45);
insert into PERSONATYPE (PersonaTypeid, BookLimit, DaysLimit) values (2, 15, 30);

insert into PERSONA (Personaid, FirstName, LastName, PersonaTypeId) values (1, 'Shana', 'Pidduck', 1);
insert into PERSONA (Personaid, FirstName, LastName, PersonaTypeId) values (2, 'Lorianna', 'Heads', 2);
insert into PERSONA (Personaid, FirstName, LastName, PersonaTypeId) values (3, 'Dante', 'Meynell', 2);
insert into PERSONA (Personaid, FirstName, LastName, PersonaTypeId) values (4, 'Osbourn', 'Frankton', 1);
insert into PERSONA (Personaid, FirstName, LastName, PersonaTypeId) values (5, 'Tobias', 'Bortoletti', 1);
insert into PERSONA (Personaid, FirstName, LastName, PersonaTypeId) values (6, 'Jon', 'Aire', 2);
insert into PERSONA (Personaid, FirstName, LastName, PersonaTypeId) values (7, 'Cindra', 'Kunes', 2);
insert into PERSONA (Personaid, FirstName, LastName, PersonaTypeId) values (8, 'Ella', 'Tunsley', 1);
insert into PERSONA (Personaid, FirstName, LastName, PersonaTypeId) values (9, 'Humbert', 'D''Adda', 1);
insert into PERSONA (Personaid, FirstName, LastName, PersonaTypeId) values (10, 'Gabrielle', 'Motten', 1);
insert into PERSONA (Personaid, FirstName, LastName, PersonaTypeId) values (11, 'Jaclyn', 'Bessey', 2);
insert into PERSONA (Personaid, FirstName, LastName, PersonaTypeId) values (12, 'Jerry', 'Uwins', 2);
insert into PERSONA (Personaid, FirstName, LastName, PersonaTypeId) values (13, 'Walther', 'Coldrick', 1);
insert into PERSONA (Personaid, FirstName, LastName, PersonaTypeId) values (14, 'Reid', 'Halliburton', 2);
insert into PERSONA (Personaid, FirstName, LastName, PersonaTypeId) values (15, 'Gena', 'Hatherell', 2);
insert into PERSONA (Personaid, FirstName, LastName, PersonaTypeId) values (16, 'Dela', 'Lafee', 1);
insert into PERSONA (Personaid, FirstName, LastName, PersonaTypeId) values (17, 'Trey', 'Tanser', 2);
insert into PERSONA (Personaid, FirstName, LastName, PersonaTypeId) values (18, 'Rozamond', 'Trouncer', 2);
insert into PERSONA (Personaid, FirstName, LastName, PersonaTypeId) values (19, 'Patti', 'Welbrock', 1);
insert into PERSONA (Personaid, FirstName, LastName, PersonaTypeId) values (20, 'Pearce', 'Casaletto', 1);
insert into PERSONA (Personaid, FirstName, LastName, PersonaTypeId) values (21, 'Carlin', 'Gliddon', 1);
insert into PERSONA (Personaid, FirstName, LastName, PersonaTypeId) values (22, 'Brook', 'Hexham', 2);
insert into PERSONA (Personaid, FirstName, LastName, PersonaTypeId) values (23, 'Leo', 'MacGiany', 2);
insert into PERSONA (Personaid, FirstName, LastName, PersonaTypeId) values (24, 'Kareem', 'Scaife', 2);
insert into PERSONA (Personaid, FirstName, LastName, PersonaTypeId) values (25, 'Karel', 'Hover', 1);
insert into PERSONA (Personaid, FirstName, LastName, PersonaTypeId) values (26, 'Myrtle', 'Binks', 1);
insert into PERSONA (Personaid, FirstName, LastName, PersonaTypeId) values (27, 'Jehu', 'Blethyn', 2);
insert into PERSONA (Personaid, FirstName, LastName, PersonaTypeId) values (28, 'Quent', 'Gonnard', 2);
insert into PERSONA (Personaid, FirstName, LastName, PersonaTypeId) values (29, 'Inger', 'Borris', 1);
insert into PERSONA (Personaid, FirstName, LastName, PersonaTypeId) values (30, 'Blair', 'Vina', 1);
insert into PERSONA (Personaid, FirstName, LastName, PersonaTypeId) values (31, 'Chlo', 'Wheelhouse', 1);
insert into PERSONA (Personaid, FirstName, LastName, PersonaTypeId) values (32, 'Hilton', 'Lafranconi', 1);
insert into PERSONA (Personaid, FirstName, LastName, PersonaTypeId) values (33, 'Hoebart', 'Peal', 2);
insert into PERSONA (Personaid, FirstName, LastName, PersonaTypeId) values (34, 'Tish', 'Brizell', 2);
insert into PERSONA (Personaid, FirstName, LastName, PersonaTypeId) values (35, 'Darrick', 'Ghioni', 1);
insert into PERSONA (Personaid, FirstName, LastName, PersonaTypeId) values (36, 'Tibold', 'Clarricoates', 1);
insert into PERSONA (Personaid, FirstName, LastName, PersonaTypeId) values (37, 'Lida', 'Sarney', 1);
insert into PERSONA (Personaid, FirstName, LastName, PersonaTypeId) values (38, 'Lorita', 'Egre', 2);
insert into PERSONA (Personaid, FirstName, LastName, PersonaTypeId) values (39, 'Hilary', 'Eplett', 2);
insert into PERSONA (Personaid, FirstName, LastName, PersonaTypeId) values (40, 'Melloney', 'Pirazzi', 1);
insert into PERSONA (Personaid, FirstName, LastName, PersonaTypeId) values (41, 'Ardelis', 'Leggat', 1);
insert into PERSONA (Personaid, FirstName, LastName, PersonaTypeId) values (42, 'Rochella', 'Littell', 1);
insert into PERSONA (Personaid, FirstName, LastName, PersonaTypeId) values (43, 'Marina', 'Kalkhoven', 1);
insert into PERSONA (Personaid, FirstName, LastName, PersonaTypeId) values (44, 'Erhard', 'Madeley', 1);
insert into PERSONA (Personaid, FirstName, LastName, PersonaTypeId) values (45, 'Puff', 'Deex', 2);
insert into PERSONA (Personaid, FirstName, LastName, PersonaTypeId) values (46, 'Mareah', 'Boldero', 2);
insert into PERSONA (Personaid, FirstName, LastName, PersonaTypeId) values (47, 'Amelie', 'Woolford', 1);
insert into PERSONA (Personaid, FirstName, LastName, PersonaTypeId) values (48, 'Austin', 'McFie', 1);
insert into PERSONA (Personaid, FirstName, LastName, PersonaTypeId) values (49, 'Jeanna', 'Gudahy', 2);
insert into PERSONA (Personaid, FirstName, LastName, PersonaTypeId) values (50, 'Iggy', 'Skyme', 2);
insert into PERSONA (Personaid, FirstName, LastName, PersonaTypeId) values (51, 'Gwendolin', 'Hearons', 2);
insert into PERSONA (Personaid, FirstName, LastName, PersonaTypeId) values (52, 'Wilfred', 'Ruddlesden', 2);
insert into PERSONA (Personaid, FirstName, LastName, PersonaTypeId) values (53, 'Jose', 'Ramsey', 1);
insert into PERSONA (Personaid, FirstName, LastName, PersonaTypeId) values (54, 'Maddie', 'Drowsfield', 2);
insert into PERSONA (Personaid, FirstName, LastName, PersonaTypeId) values (55, 'Benita', 'McQuarrie', 2);
insert into PERSONA (Personaid, FirstName, LastName, PersonaTypeId) values (56, 'Ethelbert', 'Minichillo', 1);
insert into PERSONA (Personaid, FirstName, LastName, PersonaTypeId) values (57, 'Floria', 'Domico', 2);
insert into PERSONA (Personaid, FirstName, LastName, PersonaTypeId) values (58, 'Ede', 'Lusty', 1);
insert into PERSONA (Personaid, FirstName, LastName, PersonaTypeId) values (59, 'Lynea', 'Duggen', 1);
insert into PERSONA (Personaid, FirstName, LastName, PersonaTypeId) values (60, 'Salmon', 'Wilde', 1);
insert into PERSONA (Personaid, FirstName, LastName, PersonaTypeId) values (61, 'Garrek', 'Deadman', 1);
insert into PERSONA (Personaid, FirstName, LastName, PersonaTypeId) values (62, 'Blakeley', 'Whiscard', 1);
insert into PERSONA (Personaid, FirstName, LastName, PersonaTypeId) values (63, 'Weber', 'Griffey', 1);
insert into PERSONA (Personaid, FirstName, LastName, PersonaTypeId) values (64, 'Verney', 'McKue', 1);
insert into PERSONA (Personaid, FirstName, LastName, PersonaTypeId) values (65, 'Morgen', 'William', 2);
insert into PERSONA (Personaid, FirstName, LastName, PersonaTypeId) values (66, 'Hastie', 'Brook', 2);
insert into PERSONA (Personaid, FirstName, LastName, PersonaTypeId) values (67, 'Agace', 'Burnip', 2);
insert into PERSONA (Personaid, FirstName, LastName, PersonaTypeId) values (68, 'Vita', 'Alwin', 1);
insert into PERSONA (Personaid, FirstName, LastName, PersonaTypeId) values (69, 'Giuditta', 'Bridle', 2);
insert into PERSONA (Personaid, FirstName, LastName, PersonaTypeId) values (70, 'Tyrone', 'Olivella', 1);
insert into PERSONA (Personaid, FirstName, LastName, PersonaTypeId) values (71, 'Marchelle', 'Pallasch', 2);
insert into PERSONA (Personaid, FirstName, LastName, PersonaTypeId) values (72, 'Riobard', 'Clymo', 1);
insert into PERSONA (Personaid, FirstName, LastName, PersonaTypeId) values (73, 'Natalie', 'Sandeford', 2);
insert into PERSONA (Personaid, FirstName, LastName, PersonaTypeId) values (74, 'Dorrie', 'Hales', 1);
insert into PERSONA (Personaid, FirstName, LastName, PersonaTypeId) values (75, 'Alfons', 'Elland', 2);
insert into PERSONA (Personaid, FirstName, LastName, PersonaTypeId) values (76, 'Skyler', 'Palmby', 1);
insert into PERSONA (Personaid, FirstName, LastName, PersonaTypeId) values (77, 'Rici', 'Calverley', 2);
insert into PERSONA (Personaid, FirstName, LastName, PersonaTypeId) values (78, 'Krissy', 'Crotch', 2);
insert into PERSONA (Personaid, FirstName, LastName, PersonaTypeId) values (79, 'Duncan', 'Lightoller', 1);
insert into PERSONA (Personaid, FirstName, LastName, PersonaTypeId) values (80, 'Reinald', 'Winridge', 2);
insert into PERSONA (Personaid, FirstName, LastName, PersonaTypeId) values (81, 'Margarette', 'Berends', 1);
insert into PERSONA (Personaid, FirstName, LastName, PersonaTypeId) values (82, 'Clim', 'Cootes', 2);
insert into PERSONA (Personaid, FirstName, LastName, PersonaTypeId) values (83, 'Dolley', 'Rozanski', 1);
insert into PERSONA (Personaid, FirstName, LastName, PersonaTypeId) values (84, 'Marleah', 'Woodyatt', 1);
insert into PERSONA (Personaid, FirstName, LastName, PersonaTypeId) values (85, 'Emmey', 'Surby', 2);
insert into PERSONA (Personaid, FirstName, LastName, PersonaTypeId) values (86, 'Garrard', 'Bruhnicke', 1);
insert into PERSONA (Personaid, FirstName, LastName, PersonaTypeId) values (87, 'Kiley', 'Daft', 1);
insert into PERSONA (Personaid, FirstName, LastName, PersonaTypeId) values (88, 'Roosevelt', 'Moynihan', 2);
insert into PERSONA (Personaid, FirstName, LastName, PersonaTypeId) values (89, 'Gray', 'Frankton', 1);
insert into PERSONA (Personaid, FirstName, LastName, PersonaTypeId) values (90, 'Kip', 'Rentoll', 1);
insert into PERSONA (Personaid, FirstName, LastName, PersonaTypeId) values (91, 'Muffin', 'Alcoran', 2);
insert into PERSONA (Personaid, FirstName, LastName, PersonaTypeId) values (92, 'Robbin', 'Sterrick', 1);
insert into PERSONA (Personaid, FirstName, LastName, PersonaTypeId) values (93, 'Doralynn', 'Chastang', 1);
insert into PERSONA (Personaid, FirstName, LastName, PersonaTypeId) values (94, 'Timmy', 'Kenn', 1);
insert into PERSONA (Personaid, FirstName, LastName, PersonaTypeId) values (95, 'Cobby', 'Shakesby', 1;
insert into PERSONA (Personaid, FirstName, LastName, PersonaTypeId) values (96, 'Chaim', 'Pawlik', 2);
insert into PERSONA (Personaid, FirstName, LastName, PersonaTypeId) values (97, 'Gifford', 'Cattach', 2);
insert into PERSONA (Personaid, FirstName, LastName, PersonaTypeId) values (98, 'Arlette', 'Merring', 2);
insert into PERSONA (Personaid, FirstName, LastName, PersonaTypeId) values (99, 'Dorotea', 'Colquyte', 2);
insert into PERSONA (Personaid, FirstName, LastName, PersonaTypeId) values (100, 'Merlina', 'Tourmell', 2);

insert into BOOK (Bookid, Title, Copies, Publisher) values (1, 'Gold', 20, 'Beer LLC');
insert into BOOK (Bookid, Title, Copies, Publisher) values (2, 'Year of the Yao, The', 4, 'Baumbach, Harvey and Nienow');
insert into BOOK (Bookid, Title, Copies, Publisher) values (3, 'Tremors II: Aftershocks', 18, 'Bruen and Sons');
insert into BOOK (Bookid, Title, Copies, Publisher) values (4, 'Letter, The', 14, 'Robel, Roob and Orn');
insert into BOOK (Bookid, Title, Copies, Publisher) values (5, 'Perfect Score, The', 1, 'Leannon-Hodkiewicz');
insert into BOOK (Bookid, Title, Copies, Publisher) values (6, 'Newton Boys, The', 9, 'Sauer-Rosenbaum');
insert into BOOK (Bookid, Title, Copies, Publisher) values (7, 'Because You''re Mine', 14, 'McCullough, Ullrich and Sporer');
insert into BOOK (Bookid, Title, Copies, Publisher) values (8, 'Mission Congo', 27, 'Kertzmann and Sons');
insert into BOOK (Bookid, Title, Copies, Publisher) values (9, 'Lady Snowblood (Shurayukihime)', 14, 'Wolff, Aufderhar and Barton');
insert into BOOK (Bookid, Title, Copies, Publisher) values (10, 'Mystics in Bali (Leák)', 27, 'Feeney-White');
insert into BOOK (Bookid, Title, Copies, Publisher) values (11, 'Easier with Practice', 20, 'Ullrich LLC');
insert into BOOK (Bookid, Title, Copies, Publisher) values (12, 'No Man''s Land', 26, 'Botsford, Wilkinson and Lockman');
insert into BOOK (Bookid, Title, Copies, Publisher) values (13, 'Iron Sky', 19, 'Runolfsson, Romaguera and Shanahan');
insert into BOOK (Bookid, Title, Copies, Publisher) values (14, 'The Butterfly Effect', 17, 'Schultz-Schinner');
insert into BOOK (Bookid, Title, Copies, Publisher) values (15, 'Private Parts', 13, 'Funk-Roberts');
insert into BOOK (Bookid, Title, Copies, Publisher) values (16, 'Homevideo', 25, 'Fisher, Kling and Donnelly');
insert into BOOK (Bookid, Title, Copies, Publisher) values (17, 'Son of Godzilla (Kaijûtô no kessen: Gojira no musuko)', 29, 'Torp-Heidenreich');
insert into BOOK (Bookid, Title, Copies, Publisher) values (18, 'You Killed Me First', 4, 'Steuber Group');
insert into BOOK (Bookid, Title, Copies, Publisher) values (19, 'Things You Can Tell Just by Looking at Her', 25, 'Sporer, Ortiz and Robel');
insert into BOOK (Bookid, Title, Copies, Publisher) values (20, 'Pied Piper, The (Pied Piper of Hamelin, The)', 6, 'Predovic-Braun');
insert into BOOK (Bookid, Title, Copies, Publisher) values (21, 'Eight Miles High (Das wilde Leben)', 23, 'Dibbert-Hills');
insert into BOOK (Bookid, Title, Copies, Publisher) values (22, 'Beethoven''s 5th', 8, 'Greenholt Inc');
insert into BOOK (Bookid, Title, Copies, Publisher) values (23, 'Avengers, The', 6, 'Kshlerin-Herzog');
insert into BOOK (Bookid, Title, Copies, Publisher) values (24, 'Surviving Picasso', 24, 'West-Ritchie');
insert into BOOK (Bookid, Title, Copies, Publisher) values (25, 'Sincerely Yours', 8, 'Hagenes, Hintz and Kerluke');
insert into BOOK (Bookid, Title, Copies, Publisher) values (26, 'Emma''s Bliss (Emmas Glück)', 8, 'Bergnaum and Sons');
insert into BOOK (Bookid, Title, Copies, Publisher) values (27, 'Attila (Attila Flagello di Dio)', 1, 'Haley-Jones');
insert into BOOK (Bookid, Title, Copies, Publisher) values (28, 'Petrified Forest, The', 19, 'Haag Group');
insert into BOOK (Bookid, Title, Copies, Publisher) values (29, 'Hound of the Baskervilles, The', 8, 'Dicki Inc');
insert into BOOK (Bookid, Title, Copies, Publisher) values (30, 'Assembly (Ji jie hao) ', 9, 'Ruecker, Heathcote and Parisian');
insert into BOOK (Bookid, Title, Copies, Publisher) values (31, 'Possible Worlds', 23, 'Deckow-Barton');
insert into BOOK (Bookid, Title, Copies, Publisher) values (32, 'Going the Distance', 8, 'Stroman-McLaughlin');
insert into BOOK (Bookid, Title, Copies, Publisher) values (33, 'Rashomon (Rashômon)', 20, 'Heidenreich-Keeling');
insert into BOOK (Bookid, Title, Copies, Publisher) values (34, 'Full Moon High', 15, 'Roberts-Green');
insert into BOOK (Bookid, Title, Copies, Publisher) values (35, 'Thing: Terror Takes Shape, The', 25, 'Jerde-Borer');
insert into BOOK (Bookid, Title, Copies, Publisher) values (36, 'Reap the Wild Wind', 21, 'Bogan-Hayes');
insert into BOOK (Bookid, Title, Copies, Publisher) values (37, 'Bad Day at Black Rock', 14, 'Moore Inc');
insert into BOOK (Bookid, Title, Copies, Publisher) values (38, 'Playing by Heart', 7, 'Stracke Inc');
insert into BOOK (Bookid, Title, Copies, Publisher) values (39, 'Down From the Mountain', 15, 'Gusikowski, Greenholt and Kunde');
insert into BOOK (Bookid, Title, Copies, Publisher) values (40, 'Second Jungle Book: Mowgli & Baloo, The', 24, 'Rolfson Inc');
insert into BOOK (Bookid, Title, Copies, Publisher) values (41, 'Catch-22', 24, 'O''Conner, Trantow and Lebsack');
insert into BOOK (Bookid, Title, Copies, Publisher) values (42, 'Deadly Surveillance', 10, 'Dickens-VonRueden');
insert into BOOK (Bookid, Title, Copies, Publisher) values (43, 'Zeus and Roxanne', 3, 'Sawayn, Rempel and Doyle');
insert into BOOK (Bookid, Title, Copies, Publisher) values (44, '1911 (Xinhai geming)', 7, 'Hessel, Bayer and Keeling');
insert into BOOK (Bookid, Title, Copies, Publisher) values (45, 'Secret, The', 22, 'Larkin and Sons');
insert into BOOK (Bookid, Title, Copies, Publisher) values (46, 'Million to Juan, A', 13, 'Wilkinson-Schulist');
insert into BOOK (Bookid, Title, Copies, Publisher) values (47, 'Burke and Hare', 18, 'Halvorson and Sons');
insert into BOOK (Bookid, Title, Copies, Publisher) values (48, 'Karla', 12, 'Quigley-Hartmann');
insert into BOOK (Bookid, Title, Copies, Publisher) values (49, '6ixtynin9 (Ruang Talok 69)', 3, 'Gleason, Nolan and Koepp');
insert into BOOK (Bookid, Title, Copies, Publisher) values (50, 'Face of Another, The (Tanin no kao)', 8, 'Miller, Zulauf and Grimes');
insert into BOOK (Bookid, Title, Copies, Publisher) values (51, 'Heavyweights (Heavy Weights)', 26, 'Barton and Sons');
insert into BOOK (Bookid, Title, Copies, Publisher) values (52, 'Promised Life, The (Vie promise, La)', 25, 'Walker-Boyle');
insert into BOOK (Bookid, Title, Copies, Publisher) values (53, 'December 7th', 23, 'Brakus, Thompson and Zemlak');
insert into BOOK (Bookid, Title, Copies, Publisher) values (54, 'And the Band Played On', 28, 'Kreiger-Runolfsdottir');
insert into BOOK (Bookid, Title, Copies, Publisher) values (55, 'Particle Fever', 13, 'Morissette and Sons');
insert into BOOK (Bookid, Title, Copies, Publisher) values (56, 'Come Out and Play', 15, 'Schmeler-Keebler');
insert into BOOK (Bookid, Title, Copies, Publisher) values (57, 'Amsterdamned', 4, 'Herzog, Bashirian and Grimes');
insert into BOOK (Bookid, Title, Copies, Publisher) values (58, 'Thin Blue Lie, The', 9, 'Wolf-Ritchie');
insert into BOOK (Bookid, Title, Copies, Publisher) values (59, 'Steamboy (Suchîmubôi)', 9, 'Senger-MacGyver');
insert into BOOK (Bookid, Title, Copies, Publisher) values (60, 'Thirteen, The (Trinadtsat)', 15, 'Leannon, Beahan and Feeney');
insert into BOOK (Bookid, Title, Copies, Publisher) values (61, 'Eat', 6, 'Wuckert Inc');
insert into BOOK (Bookid, Title, Copies, Publisher) values (62, 'Torn Curtain', 3, 'Schmidt, Hintz and Spinka');
insert into BOOK (Bookid, Title, Copies, Publisher) values (63, 'A Short History of Decay', 26, 'Cremin, Bartoletti and Braun');
insert into BOOK (Bookid, Title, Copies, Publisher) values (64, 'World of Kanako, The (Kawaki.)', 29, 'Bogisich, Parisian and Dickens');
insert into BOOK (Bookid, Title, Copies, Publisher) values (65, 'Killer Movie', 11, 'Boehm-Hahn');
insert into BOOK (Bookid, Title, Copies, Publisher) values (66, 'Phantom, The', 28, 'Crona-Zulauf');
insert into BOOK (Bookid, Title, Copies, Publisher) values (67, 'A Pigeon Sat on a Branch Reflecting on Existence', 21, 'Nikolaus-Schuster');
insert into BOOK (Bookid, Title, Copies, Publisher) values (68, 'Mr. Wonderful', 15, 'Kulas-Balistreri');
insert into BOOK (Bookid, Title, Copies, Publisher) values (69, 'All About Lily Chou-Chou (Riri Shushu no subete)', 18, 'Schaden-Trantow');
insert into BOOK (Bookid, Title, Copies, Publisher) values (70, 'Year of the Dog', 2, 'Anderson, Mayer and Ritchie');
insert into BOOK (Bookid, Title, Copies, Publisher) values (71, 'Wicker Man, The', 13, 'Crooks, Ratke and Jerde');
insert into BOOK (Bookid, Title, Copies, Publisher) values (72, 'Svampe', 6, 'King, Swift and Hansen');
insert into BOOK (Bookid, Title, Copies, Publisher) values (73, 'My Wife Is a Gangster 2 (Jopog manura 2: Dolaon jeonseol)', 22, 'Fay, Luettgen and Cassin');
insert into BOOK (Bookid, Title, Copies, Publisher) values (74, 'Breathe In', 12, 'Weimann, Jaskolski and Denesik');
insert into BOOK (Bookid, Title, Copies, Publisher) values (75, 'Tron: Legacy', 20, 'Howe LLC');
insert into BOOK (Bookid, Title, Copies, Publisher) values (76, 'Sure Thing, The', 20, 'Muller-Sporer');
insert into BOOK (Bookid, Title, Copies, Publisher) values (77, 'Beneath the Valley of the Ultra-Vixens', 21, 'Lueilwitz and Sons');
insert into BOOK (Bookid, Title, Copies, Publisher) values (78, 'Forget Baghdad: Jews and Arabs - The Iraqi Connection', 28, 'Kozey-Berge');
insert into BOOK (Bookid, Title, Copies, Publisher) values (79, 'Wreck-It Ralph', 10, 'Conn LLC');
insert into BOOK (Bookid, Title, Copies, Publisher) values (80, 'Mark, The', 17, 'Bergstrom, Bednar and Heller');
insert into BOOK (Bookid, Title, Copies, Publisher) values (81, 'Kolya (Kolja)', 12, 'Boyer Group');
insert into BOOK (Bookid, Title, Copies, Publisher) values (82, 'Mercy ', 22, 'Hagenes, Rath and Hintz');
insert into BOOK (Bookid, Title, Copies, Publisher) values (83, 'Reckless', 16, 'Schmeler Group');
insert into BOOK (Bookid, Title, Copies, Publisher) values (84, 'True Grit', 19, 'Johns Inc');
insert into BOOK (Bookid, Title, Copies, Publisher) values (85, 'Chopping Mall (a.k.a. Killbots)', 6, 'Feest, Marquardt and Bode');
insert into BOOK (Bookid, Title, Copies, Publisher) values (86, 'Stuck on You', 29, 'Herzog LLC');
insert into BOOK (Bookid, Title, Copies, Publisher) values (87, 'Spy Who Came in from the Cold, The', 14, 'Flatley LLC');
insert into BOOK (Bookid, Title, Copies, Publisher) values (88, 'My First War', 15, 'Carroll, Fisher and Grant');
insert into BOOK (Bookid, Title, Copies, Publisher) values (89, 'Day Night Day Night', 4, 'Reilly, Rath and Hilpert');
insert into BOOK (Bookid, Title, Copies, Publisher) values (90, 'Kicked in the Head', 3, 'Kulas, Kerluke and Oberbrunner');
insert into BOOK (Bookid, Title, Copies, Publisher) values (91, 'Underworld: Awakening', 7, 'Pacocha, Donnelly and Blick');
insert into BOOK (Bookid, Title, Copies, Publisher) values (92, 'Shoeshine (Sciuscià)', 3, 'Okuneva LLC');
insert into BOOK (Bookid, Title, Copies, Publisher) values (93, 'Montana', 25, 'Breitenberg-Spinka');
insert into BOOK (Bookid, Title, Copies, Publisher) values (94, 'How Do You Know', 8, 'Wilderman, Harris and Schuppe');
insert into BOOK (Bookid, Title, Copies, Publisher) values (95, 'Vampire Bat, The', 22, 'White Inc');
insert into BOOK (Bookid, Title, Copies, Publisher) values (96, 'Kingdom, The', 19, 'Purdy LLC');
insert into BOOK (Bookid, Title, Copies, Publisher) values (97, 'World Traveler', 2, 'Zieme and Sons');
insert into BOOK (Bookid, Title, Copies, Publisher) values (98, 'Moon Warriors, The (Zhan shen chuan shuo)', 21, 'Oberbrunner, Rowe and Wilkinson');
insert into BOOK (Bookid, Title, Copies, Publisher) values (99, 'Gigi', 29, 'Satterfield, Conroy and McDermott');
insert into BOOK (Bookid, Title, Copies, Publisher) values (100, 'Election Day', 26, 'Ferry-Kozey');

insert into AUTHOR (Authorid, FirstName, LastName) values (1, 'Baily', 'Neggrini');
insert into AUTHOR (Authorid, FirstName, LastName) values (2, 'Annecorinne', 'Nelane');
insert into AUTHOR (Authorid, FirstName, LastName) values (3, 'Cassie', 'Bril');
insert into AUTHOR (Authorid, FirstName, LastName) values (4, 'Ethelind', 'Linsley');
insert into AUTHOR (Authorid, FirstName, LastName) values (5, 'Joshua', 'Tink');
insert into AUTHOR (Authorid, FirstName, LastName) values (6, 'Coop', 'Lory');
insert into AUTHOR (Authorid, FirstName, LastName) values (7, 'Anna', 'Simic');
insert into AUTHOR (Authorid, FirstName, LastName) values (8, 'Anabelle', 'Tourner');
insert into AUTHOR (Authorid, FirstName, LastName) values (9, 'Neale', 'Cornbill');
insert into AUTHOR (Authorid, FirstName, LastName) values (10, 'Tammy', 'Mackiewicz');
insert into AUTHOR (Authorid, FirstName, LastName) values (11, 'Agnola', 'McEntegart');
insert into AUTHOR (Authorid, FirstName, LastName) values (12, 'Renaldo', 'Bridgeland');
insert into AUTHOR (Authorid, FirstName, LastName) values (13, 'Ashlie', 'Bodycombe');
insert into AUTHOR (Authorid, FirstName, LastName) values (14, 'Loraine', 'Dilke');
insert into AUTHOR (Authorid, FirstName, LastName) values (15, 'Launce', 'Dawe');
insert into AUTHOR (Authorid, FirstName, LastName) values (16, 'Fraser', 'Wrighton');
insert into AUTHOR (Authorid, FirstName, LastName) values (17, 'Blondell', 'Oakwood');
insert into AUTHOR (Authorid, FirstName, LastName) values (18, 'Rolfe', 'March');
insert into AUTHOR (Authorid, FirstName, LastName) values (19, 'Sasha', 'Vockins');
insert into AUTHOR (Authorid, FirstName, LastName) values (20, 'Rayner', 'Baynham');
insert into AUTHOR (Authorid, FirstName, LastName) values (21, 'Ardene', 'Erskine Sandys');
insert into AUTHOR (Authorid, FirstName, LastName) values (22, 'Parsifal', 'Capstaff');
insert into AUTHOR (Authorid, FirstName, LastName) values (23, 'Lock', 'Duckwith');
insert into AUTHOR (Authorid, FirstName, LastName) values (24, 'Letty', 'Pummery');
insert into AUTHOR (Authorid, FirstName, LastName) values (25, 'Nadine', 'Janic');
insert into AUTHOR (Authorid, FirstName, LastName) values (26, 'Saul', 'Phipson');
insert into AUTHOR (Authorid, FirstName, LastName) values (27, 'Nikola', 'Furlow');
insert into AUTHOR (Authorid, FirstName, LastName) values (28, 'Gardener', 'Graeser');
insert into AUTHOR (Authorid, FirstName, LastName) values (29, 'Dorian', 'Vaadeland');
insert into AUTHOR (Authorid, FirstName, LastName) values (30, 'Giralda', 'Deely');
insert into AUTHOR (Authorid, FirstName, LastName) values (31, 'Sibyl', 'Josovitz');
insert into AUTHOR (Authorid, FirstName, LastName) values (32, 'Gordy', 'Bartle');
insert into AUTHOR (Authorid, FirstName, LastName) values (33, 'Cole', 'Shallo');
insert into AUTHOR (Authorid, FirstName, LastName) values (34, 'Francklin', 'Philipsen');
insert into AUTHOR (Authorid, FirstName, LastName) values (35, 'Edeline', 'Kobel');
insert into AUTHOR (Authorid, FirstName, LastName) values (36, 'Sansone', 'O''Carran');
insert into AUTHOR (Authorid, FirstName, LastName) values (37, 'Constantine', 'Crimmins');
insert into AUTHOR (Authorid, FirstName, LastName) values (38, 'Kari', 'Thaxton');
insert into AUTHOR (Authorid, FirstName, LastName) values (39, 'Yasmin', 'Leng');
insert into AUTHOR (Authorid, FirstName, LastName) values (40, 'Gwendolyn', 'Jell');
insert into AUTHOR (Authorid, FirstName, LastName) values (41, 'Todd', 'Palister');
insert into AUTHOR (Authorid, FirstName, LastName) values (42, 'Robby', 'Couth');
insert into AUTHOR (Authorid, FirstName, LastName) values (43, 'Mari', 'Cairney');
insert into AUTHOR (Authorid, FirstName, LastName) values (44, 'Tiler', 'Byrom');
insert into AUTHOR (Authorid, FirstName, LastName) values (45, 'Tyrus', 'Cornilleau');
insert into AUTHOR (Authorid, FirstName, LastName) values (46, 'Mirabel', 'Norster');
insert into AUTHOR (Authorid, FirstName, LastName) values (47, 'Bennie', 'Witchard');
insert into AUTHOR (Authorid, FirstName, LastName) values (48, 'Nellie', 'Punter');
insert into AUTHOR (Authorid, FirstName, LastName) values (49, 'Malachi', 'Barde');
insert into AUTHOR (Authorid, FirstName, LastName) values (50, 'Tomkin', 'MacAskill');
insert into AUTHOR (Authorid, FirstName, LastName) values (51, 'Carmita', 'Decayette');
insert into AUTHOR (Authorid, FirstName, LastName) values (52, 'Reeba', 'Killingworth');
insert into AUTHOR (Authorid, FirstName, LastName) values (53, 'Kippie', 'Teek');
insert into AUTHOR (Authorid, FirstName, LastName) values (54, 'Lucas', 'Whitebrook');
insert into AUTHOR (Authorid, FirstName, LastName) values (55, 'Barris', 'Connow');
insert into AUTHOR (Authorid, FirstName, LastName) values (56, 'Hunter', 'Backson');
insert into AUTHOR (Authorid, FirstName, LastName) values (57, 'Tamra', 'MacCleay');
insert into AUTHOR (Authorid, FirstName, LastName) values (58, 'Chelsae', 'Leffek');
insert into AUTHOR (Authorid, FirstName, LastName) values (59, 'Charlton', 'Stower');
insert into AUTHOR (Authorid, FirstName, LastName) values (60, 'Iorgo', 'Bendare');
insert into AUTHOR (Authorid, FirstName, LastName) values (61, 'Derek', 'Wawer');
insert into AUTHOR (Authorid, FirstName, LastName) values (62, 'Marie-ann', 'Bischop');
insert into AUTHOR (Authorid, FirstName, LastName) values (63, 'Northrop', 'Luther');
insert into AUTHOR (Authorid, FirstName, LastName) values (64, 'Hamlen', 'Jent');
insert into AUTHOR (Authorid, FirstName, LastName) values (65, 'Emmett', 'Kolak');
insert into AUTHOR (Authorid, FirstName, LastName) values (66, 'Ezekiel', 'Friett');
insert into AUTHOR (Authorid, FirstName, LastName) values (67, 'Dannel', 'Battisson');
insert into AUTHOR (Authorid, FirstName, LastName) values (68, 'Ravi', 'Grinston');
insert into AUTHOR (Authorid, FirstName, LastName) values (69, 'Feliks', 'Breeton');
insert into AUTHOR (Authorid, FirstName, LastName) values (70, 'Binny', 'Delacourt');
insert into AUTHOR (Authorid, FirstName, LastName) values (71, 'Kin', 'Levine');
insert into AUTHOR (Authorid, FirstName, LastName) values (72, 'Sidnee', 'Vannacci');
insert into AUTHOR (Authorid, FirstName, LastName) values (73, 'Mavra', 'Dmitrovic');
insert into AUTHOR (Authorid, FirstName, LastName) values (74, 'Lamont', 'Renhard');
insert into AUTHOR (Authorid, FirstName, LastName) values (75, 'Nari', 'Kleinhaus');
insert into AUTHOR (Authorid, FirstName, LastName) values (76, 'Debra', 'O''Dyvoy');
insert into AUTHOR (Authorid, FirstName, LastName) values (77, 'Pasquale', 'Sjollema');
insert into AUTHOR (Authorid, FirstName, LastName) values (78, 'Josey', 'Brabban');
insert into AUTHOR (Authorid, FirstName, LastName) values (79, 'Melisandra', 'Moatt');
insert into AUTHOR (Authorid, FirstName, LastName) values (80, 'Rachael', 'Tremlett');
insert into AUTHOR (Authorid, FirstName, LastName) values (81, 'Pooh', 'Dreigher');
insert into AUTHOR (Authorid, FirstName, LastName) values (82, 'Esma', 'Bartlomiej');
insert into AUTHOR (Authorid, FirstName, LastName) values (83, 'Chauncey', 'Shedd');
insert into AUTHOR (Authorid, FirstName, LastName) values (84, 'Katusha', 'Sweetenham');
insert into AUTHOR (Authorid, FirstName, LastName) values (85, 'Blinni', 'McLauchlin');
insert into AUTHOR (Authorid, FirstName, LastName) values (86, 'Constantine', 'Caldicott');
insert into AUTHOR (Authorid, FirstName, LastName) values (87, 'Lory', 'Pavis');
insert into AUTHOR (Authorid, FirstName, LastName) values (88, 'Court', 'Wilton');
insert into AUTHOR (Authorid, FirstName, LastName) values (89, 'Christoper', 'Hukin');
insert into AUTHOR (Authorid, FirstName, LastName) values (90, 'Dottie', 'Hanretty');
insert into AUTHOR (Authorid, FirstName, LastName) values (91, 'Normie', 'Trinke');
insert into AUTHOR (Authorid, FirstName, LastName) values (92, 'Sigismund', 'True');
insert into AUTHOR (Authorid, FirstName, LastName) values (93, 'Allianora', 'Sheran');
insert into AUTHOR (Authorid, FirstName, LastName) values (94, 'Sybil', 'Tappor');
insert into AUTHOR (Authorid, FirstName, LastName) values (95, 'Niven', 'Bradder');
insert into AUTHOR (Authorid, FirstName, LastName) values (96, 'Ezechiel', 'Scrannage');
insert into AUTHOR (Authorid, FirstName, LastName) values (97, 'Ring', 'Meugens');
insert into AUTHOR (Authorid, FirstName, LastName) values (98, 'Amelie', 'Greveson');
insert into AUTHOR (Authorid, FirstName, LastName) values (99, 'Sigrid', 'Blay');
insert into AUTHOR (Authorid, FirstName, LastName) values (100, 'Roselia', 'Malec');

insert into PERSONABOOK (PersonaId, BookId, AcqDate, ReturnDate, Fine) values (68, 100, '3/1/2021', 2021-03-06 08:49:30 UTC, 60);
insert into PERSONABOOK (PersonaId, BookId, AcqDate, ReturnDate, Fine) values (26, 55, '11/28/2020', 2020-12-03 06:47:57 UTC, 45);
insert into PERSONABOOK (PersonaId, BookId, AcqDate, ReturnDate, Fine) values (76, 86, '2/7/2021', 2021-02-10 13:11:01 UTC, 45);
insert into PERSONABOOK (PersonaId, BookId, AcqDate, ReturnDate, Fine) values (70, 4, '5/10/2021', 2021-05-12 05:52:32 UTC, 45);
insert into PERSONABOOK (PersonaId, BookId, AcqDate, ReturnDate, Fine) values (6, 9, '9/19/2021', 2021-09-24 11:12:24 UTC, 60);
insert into PERSONABOOK (PersonaId, BookId, AcqDate, ReturnDate, Fine) values (24, 47, '2/7/2021', 2021-02-08 23:07:17 UTC, 60);
insert into PERSONABOOK (PersonaId, BookId, AcqDate, ReturnDate, Fine) values (42, 75, '10/23/2021', 2021-10-27 16:12:48 UTC, 60);
insert into PERSONABOOK (PersonaId, BookId, AcqDate, ReturnDate, Fine) values (66, 94, '4/3/2021', 2021-04-07 18:56:58 UTC, 45);
insert into PERSONABOOK (PersonaId, BookId, AcqDate, ReturnDate, Fine) values (60, 88, '3/11/2021', 2021-03-16 03:50:09 UTC, 60);
insert into PERSONABOOK (PersonaId, BookId, AcqDate, ReturnDate, Fine) values (41, 2, '9/19/2021', 2021-09-21 00:31:32 UTC, 60);
insert into PERSONABOOK (PersonaId, BookId, AcqDate, ReturnDate, Fine) values (79, 53, '11/14/2020', 2020-11-17 13:25:42 UTC, 60);
insert into PERSONABOOK (PersonaId, BookId, AcqDate, ReturnDate, Fine) values (95, 48, '2/3/2021', 2021-02-06 04:35:26 UTC, 60);
insert into PERSONABOOK (PersonaId, BookId, AcqDate, ReturnDate, Fine) values (61, 9, '10/23/2021', 2021-10-24 13:58:01 UTC, 60);
insert into PERSONABOOK (PersonaId, BookId, AcqDate, ReturnDate, Fine) values (100, 72, '12/29/2020', 2020-12-30 08:05:22 UTC, 60);
insert into PERSONABOOK (PersonaId, BookId, AcqDate, ReturnDate, Fine) values (1, 4, '1/14/2021', 2021-01-17 07:14:38 UTC, 60);
insert into PERSONABOOK (PersonaId, BookId, AcqDate, ReturnDate, Fine) values (78, 67, '6/1/2021', 2021-06-03 07:52:01 UTC, 60);
insert into PERSONABOOK (PersonaId, BookId, AcqDate, ReturnDate, Fine) values (46, 76, '11/22/2020', 2020-11-25 11:44:51 UTC, 45);
insert into PERSONABOOK (PersonaId, BookId, AcqDate, ReturnDate, Fine) values (22, 87, '8/21/2021', 2021-08-25 17:27:03 UTC, 45);
insert into PERSONABOOK (PersonaId, BookId, AcqDate, ReturnDate, Fine) values (16, 1, '7/15/2021', 2021-07-16 18:21:51 UTC, 45);
insert into PERSONABOOK (PersonaId, BookId, AcqDate, ReturnDate, Fine) values (34, 67, '1/13/2021', 2021-01-14 03:44:10 UTC, 60);
insert into PERSONABOOK (PersonaId, BookId, AcqDate, ReturnDate, Fine) values (76, 58, '4/26/2021', 2021-04-30 09:35:19 UTC, 60);
insert into PERSONABOOK (PersonaId, BookId, AcqDate, ReturnDate, Fine) values (45, 39, '11/10/2020', 2020-11-11 22:53:58 UTC, 60);
insert into PERSONABOOK (PersonaId, BookId, AcqDate, ReturnDate, Fine) values (77, 72, '11/11/2020', 2020-11-16 03:07:51 UTC, 60);
insert into PERSONABOOK (PersonaId, BookId, AcqDate, ReturnDate, Fine) values (29, 51, '7/8/2021', 2021-07-11 19:23:36 UTC, 60);
insert into PERSONABOOK (PersonaId, BookId, AcqDate, ReturnDate, Fine) values (50, 20, '3/2/2021', 2021-03-07 15:01:25 UTC, 45);
insert into PERSONABOOK (PersonaId, BookId, AcqDate, ReturnDate, Fine) values (31, 50, '11/6/2020', 2020-11-08 19:11:04 UTC, 45);
insert into PERSONABOOK (PersonaId, BookId, AcqDate, ReturnDate, Fine) values (52, 21, '6/25/2021', 2021-06-29 10:35:58 UTC, 60);
insert into PERSONABOOK (PersonaId, BookId, AcqDate, ReturnDate, Fine) values (100, 89, '11/22/2020', 2020-11-27 04:09:59 UTC, 60);
insert into PERSONABOOK (PersonaId, BookId, AcqDate, ReturnDate, Fine) values (39, 20, '7/6/2021', 2021-07-10 02:12:26 UTC, 45);
insert into PERSONABOOK (PersonaId, BookId, AcqDate, ReturnDate, Fine) values (72, 24, '7/26/2021', 2021-07-27 09:39:35 UTC, 45);
insert into PERSONABOOK (PersonaId, BookId, AcqDate, ReturnDate, Fine) values (91, 38, '4/11/2021', 2021-04-16 23:49:30 UTC, 45);
insert into PERSONABOOK (PersonaId, BookId, AcqDate, ReturnDate, Fine) values (49, 76, '3/7/2021', 2021-03-12 01:05:13 UTC, 60);
insert into PERSONABOOK (PersonaId, BookId, AcqDate, ReturnDate, Fine) values (67, 71, '7/24/2021', 2021-07-26 04:33:31 UTC, 60);
insert into PERSONABOOK (PersonaId, BookId, AcqDate, ReturnDate, Fine) values (2, 79, '2/10/2021', 2021-02-12 20:38:57 UTC, 45);
insert into PERSONABOOK (PersonaId, BookId, AcqDate, ReturnDate, Fine) values (6, 26, '11/2/2020', 2020-11-06 00:21:55 UTC, 45);
insert into PERSONABOOK (PersonaId, BookId, AcqDate, ReturnDate, Fine) values (27, 11, '10/11/2021', 2021-10-16 17:16:25 UTC, 45);
insert into PERSONABOOK (PersonaId, BookId, AcqDate, ReturnDate, Fine) values (46, 29, '4/19/2021', 2021-04-21 21:01:11 UTC, 60);
insert into PERSONABOOK (PersonaId, BookId, AcqDate, ReturnDate, Fine) values (85, 54, '11/7/2020', 2020-11-11 04:17:21 UTC, 45);
insert into PERSONABOOK (PersonaId, BookId, AcqDate, ReturnDate, Fine) values (75, 65, '2/15/2021', 2021-02-18 14:41:18 UTC, 60);
insert into PERSONABOOK (PersonaId, BookId, AcqDate, ReturnDate, Fine) values (13, 48, '3/16/2021', 2021-03-20 13:53:04 UTC, 60);
insert into PERSONABOOK (PersonaId, BookId, AcqDate, ReturnDate, Fine) values (60, 66, '9/7/2021', 2021-09-10 15:45:53 UTC, 45);
insert into PERSONABOOK (PersonaId, BookId, AcqDate, ReturnDate, Fine) values (28, 68, '6/17/2021', 2021-06-19 04:51:52 UTC, 60);
insert into PERSONABOOK (PersonaId, BookId, AcqDate, ReturnDate, Fine) values (99, 45, '9/9/2021', 2021-09-12 15:28:14 UTC, 60);
insert into PERSONABOOK (PersonaId, BookId, AcqDate, ReturnDate, Fine) values (59, 53, '4/14/2021', 2021-04-15 00:45:46 UTC, 60);
insert into PERSONABOOK (PersonaId, BookId, AcqDate, ReturnDate, Fine) values (61, 73, '11/8/2020', 2020-11-10 17:05:13 UTC, 60);
insert into PERSONABOOK (PersonaId, BookId, AcqDate, ReturnDate, Fine) values (81, 42, '7/2/2021', 2021-07-05 11:47:40 UTC, 60);
insert into PERSONABOOK (PersonaId, BookId, AcqDate, ReturnDate, Fine) values (8, 83, '6/26/2021', 2021-06-28 10:30:21 UTC, 60);
insert into PERSONABOOK (PersonaId, BookId, AcqDate, ReturnDate, Fine) values (95, 15, '5/23/2021', 2021-05-25 19:08:05 UTC, 60);
insert into PERSONABOOK (PersonaId, BookId, AcqDate, ReturnDate, Fine) values (76, 47, '11/4/2020', 2020-11-06 09:37:08 UTC, 60);
insert into PERSONABOOK (PersonaId, BookId, AcqDate, ReturnDate, Fine) values (64, 18, '1/2/2021', 2021-01-06 18:44:06 UTC, 45);
insert into PERSONABOOK (PersonaId, BookId, AcqDate, ReturnDate, Fine) values (25, 35, '3/17/2021', 2021-03-18 23:49:44 UTC, 60);
insert into PERSONABOOK (PersonaId, BookId, AcqDate, ReturnDate, Fine) values (43, 30, '8/9/2021', 2021-08-10 23:55:34 UTC, 60);
insert into PERSONABOOK (PersonaId, BookId, AcqDate, ReturnDate, Fine) values (80, 32, '4/29/2021', 2021-05-03 04:35:35 UTC, 60);
insert into PERSONABOOK (PersonaId, BookId, AcqDate, ReturnDate, Fine) values (53, 52, '12/2/2020', 2020-12-05 23:22:02 UTC, 45);
insert into PERSONABOOK (PersonaId, BookId, AcqDate, ReturnDate, Fine) values (84, 14, '8/13/2021', 2021-08-17 01:02:19 UTC, 60);
insert into PERSONABOOK (PersonaId, BookId, AcqDate, ReturnDate, Fine) values (49, 69, '3/19/2021', 2021-03-23 07:41:20 UTC, 45);
insert into PERSONABOOK (PersonaId, BookId, AcqDate, ReturnDate, Fine) values (36, 17, '2/21/2021', 2021-02-23 12:26:57 UTC, 45);
insert into PERSONABOOK (PersonaId, BookId, AcqDate, ReturnDate, Fine) values (92, 52, '12/16/2020', 2020-12-20 23:13:02 UTC, 60);
insert into PERSONABOOK (PersonaId, BookId, AcqDate, ReturnDate, Fine) values (81, 61, '11/22/2020', 2020-11-25 15:04:09 UTC, 60);
insert into PERSONABOOK (PersonaId, BookId, AcqDate, ReturnDate, Fine) values (96, 38, '5/16/2021', 2021-05-19 07:41:52 UTC, 45);
insert into PERSONABOOK (PersonaId, BookId, AcqDate, ReturnDate, Fine) values (47, 80, '12/2/2020', 2020-12-04 02:49:13 UTC, 45);
insert into PERSONABOOK (PersonaId, BookId, AcqDate, ReturnDate, Fine) values (78, 13, '4/16/2021', 2021-04-20 04:13:12 UTC, 45);
insert into PERSONABOOK (PersonaId, BookId, AcqDate, ReturnDate, Fine) values (35, 72, '4/1/2021', 2021-04-02 21:18:37 UTC, 45);
insert into PERSONABOOK (PersonaId, BookId, AcqDate, ReturnDate, Fine) values (49, 57, '3/8/2021', 2021-03-10 04:32:09 UTC, 45);
insert into PERSONABOOK (PersonaId, BookId, AcqDate, ReturnDate, Fine) values (12, 14, '10/2/2021', 2021-10-04 19:38:10 UTC, 45);
insert into PERSONABOOK (PersonaId, BookId, AcqDate, ReturnDate, Fine) values (77, 76, '11/3/2020', 2020-11-04 21:24:41 UTC, 45);
insert into PERSONABOOK (PersonaId, BookId, AcqDate, ReturnDate, Fine) values (36, 39, '6/24/2021', 2021-06-29 13:04:39 UTC, 45);
insert into PERSONABOOK (PersonaId, BookId, AcqDate, ReturnDate, Fine) values (84, 16, '7/8/2021', 2021-07-11 10:15:05 UTC, 45);
insert into PERSONABOOK (PersonaId, BookId, AcqDate, ReturnDate, Fine) values (77, 65, '9/25/2021', 2021-09-27 22:13:16 UTC, 45);
insert into PERSONABOOK (PersonaId, BookId, AcqDate, ReturnDate, Fine) values (11, 38, '12/6/2020', 2020-12-11 08:29:29 UTC, 60);
insert into PERSONABOOK (PersonaId, BookId, AcqDate, ReturnDate, Fine) values (58, 41, '1/21/2021', 2021-01-23 23:34:15 UTC, 45);
insert into PERSONABOOK (PersonaId, BookId, AcqDate, ReturnDate, Fine) values (67, 89, '11/3/2020', 2020-11-04 18:04:08 UTC, 60);
insert into PERSONABOOK (PersonaId, BookId, AcqDate, ReturnDate, Fine) values (80, 41, '1/6/2021', 2021-01-07 19:25:18 UTC, 45);
insert into PERSONABOOK (PersonaId, BookId, AcqDate, ReturnDate, Fine) values (19, 6, '10/23/2021', 2021-10-28 19:35:20 UTC, 60);
insert into PERSONABOOK (PersonaId, BookId, AcqDate, ReturnDate, Fine) values (88, 93, '1/28/2021', 2021-01-30 20:41:29 UTC, 45);
insert into PERSONABOOK (PersonaId, BookId, AcqDate, ReturnDate, Fine) values (80, 4, '7/31/2021', 2021-08-04 01:34:20 UTC, 45);
insert into PERSONABOOK (PersonaId, BookId, AcqDate, ReturnDate, Fine) values (43, 30, '3/9/2021', 2021-03-12 03:41:43 UTC, 60);
insert into PERSONABOOK (PersonaId, BookId, AcqDate, ReturnDate, Fine) values (37, 57, '11/16/2020', 2020-11-21 14:10:18 UTC, 45);
insert into PERSONABOOK (PersonaId, BookId, AcqDate, ReturnDate, Fine) values (10, 15, '5/4/2021', 2021-05-07 01:03:24 UTC, 45);
insert into PERSONABOOK (PersonaId, BookId, AcqDate, ReturnDate, Fine) values (100, 43, '6/13/2021', 2021-06-18 06:52:22 UTC, 45);
insert into PERSONABOOK (PersonaId, BookId, AcqDate, ReturnDate, Fine) values (60, 71, '3/8/2021', 2021-03-09 18:13:33 UTC, 60);
insert into PERSONABOOK (PersonaId, BookId, AcqDate, ReturnDate, Fine) values (85, 26, '2/21/2021', 2021-02-24 18:28:49 UTC, 45);
insert into PERSONABOOK (PersonaId, BookId, AcqDate, ReturnDate, Fine) values (93, 29, '12/16/2020', 2020-12-20 09:45:11 UTC, 60);
insert into PERSONABOOK (PersonaId, BookId, AcqDate, ReturnDate, Fine) values (26, 17, '11/14/2020', 2020-11-17 03:27:53 UTC, 60);
insert into PERSONABOOK (PersonaId, BookId, AcqDate, ReturnDate, Fine) values (41, 57, '3/7/2021', 2021-03-12 11:19:08 UTC, 60);
insert into PERSONABOOK (PersonaId, BookId, AcqDate, ReturnDate, Fine) values (73, 93, '11/28/2020', 2020-12-02 05:37:30 UTC, 45);
insert into PERSONABOOK (PersonaId, BookId, AcqDate, ReturnDate, Fine) values (33, 78, '5/26/2021', 2021-05-31 05:28:53 UTC, 45);
insert into PERSONABOOK (PersonaId, BookId, AcqDate, ReturnDate, Fine) values (27, 12, '12/16/2020', 2020-12-17 13:09:05 UTC, 60);
insert into PERSONABOOK (PersonaId, BookId, AcqDate, ReturnDate, Fine) values (40, 66, '7/18/2021', 2021-07-19 02:32:22 UTC, 60);
insert into PERSONABOOK (PersonaId, BookId, AcqDate, ReturnDate, Fine) values (41, 58, '12/12/2020', 2020-12-16 03:59:27 UTC, 45);
insert into PERSONABOOK (PersonaId, BookId, AcqDate, ReturnDate, Fine) values (81, 23, '1/30/2021', 2021-02-03 03:41:25 UTC, 60);
insert into PERSONABOOK (PersonaId, BookId, AcqDate, ReturnDate, Fine) values (31, 42, '11/29/2020', 2020-12-02 19:35:32 UTC, 45);
insert into PERSONABOOK (PersonaId, BookId, AcqDate, ReturnDate, Fine) values (43, 24, '11/16/2020', 2020-11-21 03:07:52 UTC, 60);
insert into PERSONABOOK (PersonaId, BookId, AcqDate, ReturnDate, Fine) values (85, 74, '10/6/2021', 2021-10-11 19:58:46 UTC, 60);
insert into PERSONABOOK (PersonaId, BookId, AcqDate, ReturnDate, Fine) values (86, 45, '9/21/2021', 2021-09-22 02:13:56 UTC, 45);
insert into PERSONABOOK (PersonaId, BookId, AcqDate, ReturnDate, Fine) values (55, 22, '11/20/2020', 2020-11-21 21:21:09 UTC, 45);
insert into PERSONABOOK (PersonaId, BookId, AcqDate, ReturnDate, Fine) values (37, 63, '10/7/2021', 2021-10-09 20:02:42 UTC, 45);
insert into PERSONABOOK (PersonaId, BookId, AcqDate, ReturnDate, Fine) values (10, 81, '12/11/2020', 2020-12-15 23:27:52 UTC, 60);
insert into PERSONABOOK (PersonaId, BookId, AcqDate, ReturnDate, Fine) values (84, 3, '4/15/2021', 2021-04-17 21:08:29 UTC, 45);
insert into PERSONABOOK (PersonaId, BookId, AcqDate, ReturnDate, Fine) values (32, 63, '9/11/2021', 2021-09-13 15:20:45 UTC, 45);

insert into BOOKAUTHOR (AuthorId, BookId) values (66, 65);
insert into BOOKAUTHOR (AuthorId, BookId) values (55, 6);
insert into BOOKAUTHOR (AuthorId, BookId) values (91, 72);
insert into BOOKAUTHOR (AuthorId, BookId) values (72, 90);
insert into BOOKAUTHOR (AuthorId, BookId) values (26, 92);
insert into BOOKAUTHOR (AuthorId, BookId) values (90, 66);
insert into BOOKAUTHOR (AuthorId, BookId) values (64, 42);
insert into BOOKAUTHOR (AuthorId, BookId) values (81, 18);
insert into BOOKAUTHOR (AuthorId, BookId) values (97, 72);
insert into BOOKAUTHOR (AuthorId, BookId) values (48, 30);
insert into BOOKAUTHOR (AuthorId, BookId) values (10, 94);
insert into BOOKAUTHOR (AuthorId, BookId) values (15, 86);
insert into BOOKAUTHOR (AuthorId, BookId) values (41, 7);
insert into BOOKAUTHOR (AuthorId, BookId) values (82, 35);
insert into BOOKAUTHOR (AuthorId, BookId) values (94, 51);
insert into BOOKAUTHOR (AuthorId, BookId) values (35, 10);
insert into BOOKAUTHOR (AuthorId, BookId) values (81, 36);
insert into BOOKAUTHOR (AuthorId, BookId) values (74, 91);
insert into BOOKAUTHOR (AuthorId, BookId) values (68, 20);
insert into BOOKAUTHOR (AuthorId, BookId) values (91, 19);
insert into BOOKAUTHOR (AuthorId, BookId) values (48, 33);
insert into BOOKAUTHOR (AuthorId, BookId) values (76, 61);
insert into BOOKAUTHOR (AuthorId, BookId) values (52, 92);
insert into BOOKAUTHOR (AuthorId, BookId) values (9, 38);
insert into BOOKAUTHOR (AuthorId, BookId) values (58, 66);
insert into BOOKAUTHOR (AuthorId, BookId) values (45, 54);
insert into BOOKAUTHOR (AuthorId, BookId) values (25, 35);
insert into BOOKAUTHOR (AuthorId, BookId) values (19, 12);
insert into BOOKAUTHOR (AuthorId, BookId) values (17, 13);
insert into BOOKAUTHOR (AuthorId, BookId) values (88, 95);
insert into BOOKAUTHOR (AuthorId, BookId) values (73, 62);
insert into BOOKAUTHOR (AuthorId, BookId) values (40, 96);
insert into BOOKAUTHOR (AuthorId, BookId) values (10, 39);
insert into BOOKAUTHOR (AuthorId, BookId) values (65, 74);
insert into BOOKAUTHOR (AuthorId, BookId) values (2, 40);
insert into BOOKAUTHOR (AuthorId, BookId) values (61, 74);
insert into BOOKAUTHOR (AuthorId, BookId) values (74, 1);
insert into BOOKAUTHOR (AuthorId, BookId) values (95, 85);
insert into BOOKAUTHOR (AuthorId, BookId) values (36, 88);
insert into BOOKAUTHOR (AuthorId, BookId) values (74, 69);
insert into BOOKAUTHOR (AuthorId, BookId) values (94, 80);
insert into BOOKAUTHOR (AuthorId, BookId) values (81, 61);
insert into BOOKAUTHOR (AuthorId, BookId) values (3, 87);
insert into BOOKAUTHOR (AuthorId, BookId) values (68, 88);
insert into BOOKAUTHOR (AuthorId, BookId) values (85, 55);
insert into BOOKAUTHOR (AuthorId, BookId) values (95, 42);
insert into BOOKAUTHOR (AuthorId, BookId) values (71, 41);
insert into BOOKAUTHOR (AuthorId, BookId) values (31, 25);
insert into BOOKAUTHOR (AuthorId, BookId) values (39, 25);
insert into BOOKAUTHOR (AuthorId, BookId) values (79, 1);
insert into BOOKAUTHOR (AuthorId, BookId) values (48, 17);
insert into BOOKAUTHOR (AuthorId, BookId) values (54, 70);
insert into BOOKAUTHOR (AuthorId, BookId) values (78, 6);
insert into BOOKAUTHOR (AuthorId, BookId) values (76, 83);
insert into BOOKAUTHOR (AuthorId, BookId) values (65, 70);
insert into BOOKAUTHOR (AuthorId, BookId) values (15, 48);
insert into BOOKAUTHOR (AuthorId, BookId) values (57, 95);
insert into BOOKAUTHOR (AuthorId, BookId) values (48, 44);
insert into BOOKAUTHOR (AuthorId, BookId) values (87, 18);
insert into BOOKAUTHOR (AuthorId, BookId) values (91, 58);
insert into BOOKAUTHOR (AuthorId, BookId) values (71, 54);
insert into BOOKAUTHOR (AuthorId, BookId) values (81, 83);
insert into BOOKAUTHOR (AuthorId, BookId) values (27, 61);
insert into BOOKAUTHOR (AuthorId, BookId) values (7, 81);
insert into BOOKAUTHOR (AuthorId, BookId) values (9, 60);
insert into BOOKAUTHOR (AuthorId, BookId) values (37, 20);
insert into BOOKAUTHOR (AuthorId, BookId) values (37, 45);
insert into BOOKAUTHOR (AuthorId, BookId) values (24, 79);
insert into BOOKAUTHOR (AuthorId, BookId) values (20, 25);
insert into BOOKAUTHOR (AuthorId, BookId) values (90, 31);
insert into BOOKAUTHOR (AuthorId, BookId) values (39, 2);
insert into BOOKAUTHOR (AuthorId, BookId) values (23, 59);
insert into BOOKAUTHOR (AuthorId, BookId) values (97, 17);
insert into BOOKAUTHOR (AuthorId, BookId) values (64, 16);
insert into BOOKAUTHOR (AuthorId, BookId) values (56, 56);
insert into BOOKAUTHOR (AuthorId, BookId) values (64, 97);
insert into BOOKAUTHOR (AuthorId, BookId) values (53, 11);
insert into BOOKAUTHOR (AuthorId, BookId) values (32, 36);
insert into BOOKAUTHOR (AuthorId, BookId) values (51, 14);
insert into BOOKAUTHOR (AuthorId, BookId) values (8, 17);
insert into BOOKAUTHOR (AuthorId, BookId) values (83, 82);
insert into BOOKAUTHOR (AuthorId, BookId) values (10, 35);
insert into BOOKAUTHOR (AuthorId, BookId) values (38, 27);
insert into BOOKAUTHOR (AuthorId, BookId) values (21, 9);
insert into BOOKAUTHOR (AuthorId, BookId) values (81, 29);
insert into BOOKAUTHOR (AuthorId, BookId) values (12, 78);
insert into BOOKAUTHOR (AuthorId, BookId) values (67, 27);
insert into BOOKAUTHOR (AuthorId, BookId) values (67, 36);
insert into BOOKAUTHOR (AuthorId, BookId) values (38, 30);
insert into BOOKAUTHOR (AuthorId, BookId) values (17, 26);
insert into BOOKAUTHOR (AuthorId, BookId) values (11, 14);
insert into BOOKAUTHOR (AuthorId, BookId) values (87, 42);
insert into BOOKAUTHOR (AuthorId, BookId) values (79, 25);
insert into BOOKAUTHOR (AuthorId, BookId) values (98, 15);
insert into BOOKAUTHOR (AuthorId, BookId) values (46, 9);
insert into BOOKAUTHOR (AuthorId, BookId) values (80, 39);
insert into BOOKAUTHOR (AuthorId, BookId) values (41, 38);
insert into BOOKAUTHOR (AuthorId, BookId) values (53, 80);
insert into BOOKAUTHOR (AuthorId, BookId) values (87, 81);
insert into BOOKAUTHOR (AuthorId, BookId) values (12, 18);
